### ISSUE TITLE
submit.php - Werte der Felder und DB Eintrag

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib#2]
Die Werte einiger Felder werden in der DB als ID gespeichert .. besser wäre der richtige Wert -- oder?

CATEGORY
MANUFACTURER 
BRAND
Scale
Material
Packaging

**Comment by Webmeteor** [comment]
Kommt darauf an. Per Inner JOIN oder einer weiteren DB Anfrage kann man sich die Werte Anhand der ID ja holen.

**Comment by Catzenjaeger** [comment]
speichere alles alles ID ist denke auch resourceschonender. Ich kann den wert ja jederzeit als Klartext aus der anderen Tabelle holen
